version: "3.3"

services:

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
  
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: examplePassword1234
      
    ports:
      - 3307:3306

  bot:
    image: python:3.8
    container_name: bot
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      pip install -r /app/requirements.txt
      python /app/main.py

    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: examplePassword1234
      DATABASE_DB_NAME: my_database
      DATABASE_PORT: 3306
      
    depends_on:
      - database
